### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by lirnish** [UBC-MDS/music_explorer#12]
I have created the Heroku pipeline: https://dashboard.heroku.com/pipelines/1994c71a-65b9-4d1d-93bc-b8794d80392d 
Not sure if this is personal or if you guys can see it too? I have added you all as collaborators.
Any changes to the main branch should be auto-deployed to this app (theoretically): <https://music-explore.herokuapp.com/>
And later could manually promote to production: <https://musicexplore.herokuapp.com/>
(music-explorer and musicexplorer has been used so these two are the best I could find)
And seems like there is also a way to view the app before merging a pull request (123 is the pull request number): <https://music-pr-123.herokuapp.com>

Let's see if it works or not and let me know if you noticed any issue.

**Comment by dol23asuka** [comment]
Looks good to me

**Comment by lirnish** [comment]
deployed to https://music-explore.herokuapp.com/ now
